name: shackey CI

on: 
  push:
  schedule:
    - cron: '24 12 * * 2,5'
#when new src and at 12:24 on Tuesday and Friday.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: get short hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: firmware-${{ steps.vars.outputs.sha_short }}.bin
          path: .pio/build/esp32-c3-devkitm-1/firmware.bin